FROM node:latest AS base
WORKDIR /app

FROM node:latest AS build
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install

FROM base AS final
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
ENTRYPOINT npm start

